homeassistant:
  name: 智能物联
  latitude: 30.23927
  longitude: 120.05633
  elevation: 32
  unit_system: metric
  time_zone: Asia/Shanghai
  customize: !include customize.yaml

logger:
  default: warning
  logs:
    custom_components.actuator: debug
    #homeassistant.components.homekit: debug
    #pyhap: debug

system_health:

frontend:

config:

http:
  base_url: !secret http_base_url
  ssl_key: ~/.homeassistant/privkey.pem
  ssl_certificate: ~/.homeassistant/fullchain.cer

history:
  exclude:
    domains:
      - sun
      - group
      - script
      - climate
      - automation
      - input_text
      - input_select
      - input_boolean

logbook:

sun:

#tts:
  #- platform: google
  #- platform: baidu
  #  app_id: !secret baidu_app_id
  #  api_key: !secret baidu_api_key
  #  secret_key: !secret baidu_secret_key

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml

mqtt:
  broker: localhost

modbus:
  type: rtuovertcp
  host: ModBus
  port: 8899

homekit:
  filter:
    exclude_domains:
      - script
      - automation
      - input_boolean
    exclude_entities:
      - light.studyroom_light2
      - light.studyroom_light3
      - light.livingroom_light2
      - light.diningroom_light2
      - light.passage_light2
      - binary_sensor.switch_158d0001e59b33
      - binary_sensor.switch_158d000201a73f
      - switch.projector_power
      - sensor.fresher2_co2
      - climate.saswell
      - climate.saswell2
  entity_config:
    switch.outlet:
      type: outlet
    switch.outlet2:
      type: outlet
    media_player.x9300d:
      feature_list:
        - feature: on_off
    media_player.x9400e:
      feature_list:
        - feature: on_off

#TODO
# device_tracker:
# - platform: asuswrt
#   host: Router
#   username: admin
#   password: !secret http_password
#   interval_seconds: 120
#   new_device_defaults:
#     track_new_devices: false
#     hide_if_away: true

# binary_sensor:
# - platform: mqtt
#   device_class: light
#   state_topic: NodeMCU3/digital
#   payload_on: 1
#   payload_off: 0
#   name: Lightness
#   availability_topic: NodeMCU3/status

weather:
  - platform: caiyun

sensor:
  - platform: mqtt
    device_class: illuminance
    state_topic: Sonoff3/lux
    name: Studyroom Lightness
    unit_of_measurement: lm
    availability_topic: Sonoff3/status
  - platform: mqtt
    device_class: temperature
    state_topic: NodeMCU2/temperature
    name: Balcony Temperature
    unit_of_measurement: °C
    availability_topic: NodeMCU2/status
  - platform: mqtt
    device_class: humidity
    state_topic: NodeMCU2/humidity
    name: Balcony Humidity
    unit_of_measurement: '%'
    availability_topic: NodeMCU2/status
  - platform: mqtt
    state_topic: NodeMCU2/pm2dot5
    name: Balcony PM25
    unit_of_measurement: μg/m³
    availability_topic: NodeMCU2/status
  - platform: mqtt
    device_class: temperature
    state_topic: NodeMCU6/temperature
    name: Purifier6 Temperature
    unit_of_measurement: °C
    availability_topic: NodeMCU6/status
  - platform: mqtt
    device_class: humidity
    state_topic: NodeMCU6/humidity
    name: Purifier6 Humidity
    unit_of_measurement: '%'
    availability_topic: NodeMCU6/status
  - platform: mqtt
    state_topic: NodeMCU6/pm2dot5
    name: Purifier6 PM25
    unit_of_measurement: μg/m³
    availability_topic: NodeMCU6/status
  - platform: mqtt
    state_topic: NodeMCU6/co2
    name: Purifier6 CO2
    unit_of_measurement: ppm
    availability_topic: NodeMCU6/status
  - platform: mqtt
    device_class: temperature
    state_topic: NodeMCU7/temperature
    name: Purifier7 Temperature
    unit_of_measurement: °C
    availability_topic: NodeMCU7/status
  - platform: mqtt
    device_class: humidity
    state_topic: NodeMCU7/humidity
    name: Purifier7 Humidity
    unit_of_measurement: '%'
    availability_topic: NodeMCU7/status
  - platform: mqtt
    state_topic: NodeMCU7/pm2dot5
    name: Purifier7 PM25
    unit_of_measurement: μg/m³
    availability_topic: NodeMCU7/status
  # - platform: mqtt
  #   state_topic: NodeMCU7/hcho
  #   name: Purifier7 HCHO
  #   unit_of_measurement: mg/m³
  #   availability_topic: NodeMCU7/status
  - platform: mqtt
    state_topic: NodeMCU7/co2
    name: Purifier7 CO2
    unit_of_measurement: ppm
    availability_topic: NodeMCU7/status
  # - platform: phicomm
  #   name: AirCat
  #   username: !secret phicomm_username
  #   password: !secret phicomm_password
  - platform: aircat
    mac: ['B0F8931EA148', 'B0F893249132']
  - platform: template
    sensors:
      purifier_temperature:
        device_class: temperature
        friendly_name: Purifier Temperature
        value_template: '{{ states.fan.purifier.attributes.temperature }}'
        unit_of_measurement: °C
      purifier_humidity:
        device_class: humidity
        friendly_name: Purifier Humidity
        value_template: '{{ states.fan.purifier.attributes.humidity }}'
        unit_of_measurement: '%'
      purifier_pm25:
        friendly_name: Purifier PM25
        value_template: '{{ states.fan.purifier.attributes.aqi }}'
        unit_of_measurement: 'μg/m³'

      fresher_temperature:
        device_class: temperature
        friendly_name: Fresher Temperature
        value_template: '{{ states.fan.fresher.attributes.temperature }}'
        unit_of_measurement: °C
      fresher_humidity:
        device_class: humidity
        friendly_name: Fresher Humidity
        value_template: '{{ states.fan.fresher.attributes.humidity }}'
        unit_of_measurement: '%'
      fresher_pm25:
        friendly_name: Fresher PM25
        value_template: '{{ states.fan.fresher.attributes.aqi }}'
        unit_of_measurement: 'μg/m³'
      fresher_co2:
        friendly_name: Fresher CO2
        value_template: '{{ states.fan.fresher.attributes.co2 }}'
        unit_of_measurement: 'ppm'

      fresher2_temperature:
        device_class: temperature
        friendly_name: Fresher2 Temperature
        value_template: '{{ states.fan.fresher2.attributes.temperature }}'
        unit_of_measurement: °C
      fresher2_humidity:
        device_class: humidity
        friendly_name: Fresher2 Humidity
        value_template: '{{ states.fan.fresher2.attributes.humidity }}'
        unit_of_measurement: '%'
      fresher2_pm25:
        friendly_name: Fresher2 PM25
        value_template: '{{ states.fan.fresher2.attributes.aqi }}'
        unit_of_measurement: 'μg/m³'
      fresher2_co2:
        friendly_name: Fresher2 CO2
        value_template: '{{ states.fan.fresher2.attributes.co2 }}'
        unit_of_measurement: 'ppm'

      fan_temperature:
        device_class: temperature
        friendly_name: Fan Temperature
        value_template: '{{ states.fan.fan.attributes.temperature }}'
        unit_of_measurement: °C

switch:
  #TODO
  - platform: wake_on_lan
    name: Station
    mac_address: 00-11-32-6B-75-F7
    #broadcast_address: 192.168.1.255
    host: Station
    turn_off:
      service: shell_command.turn_off_station
  - platform: mqtt
    name: Washroom Fan
    state_topic: Hassmart6/relay/1
    command_topic: Hassmart6/relay/1/set
    availability_topic: Hassmart6/status
  - platform: mqtt
    name: Projector Power
    state_topic: Sonoff3/relay/1
    command_topic: Sonoff3/relay/1/set
    availability_topic: Sonoff3/status
  - platform: mqtt2
    name: Speaker
    state_topic: NodeMCU3/relay/0
    command_topic: NodeMCU3/relay/0/set
    availability_topic: NodeMCU3/status
    value_template: '{% if value == "关闭" %}toggle{% else %}ON{% endif %}'
    icon_template: '{% if value == "关闭" %}mdi:speaker-off{% elif value == "蓝牙" %}mdi:speaker-bluetooth{% elif value == "光纤" %}mdi:speaker-wireless{% elif value == "优盘" %}mdi:usb{% elif value == "辅助" %}mdi:video-input-component{% else %}mdi:speaker{% endif %}'
    payload_off: 'toggle'
  - platform: broadlink
    host: Outlet
    mac: 34:EA:34:B8:36:AC
    friendly_name: Outlet
    type: spmini2
  - platform: broadlink
    host: Outlet2
    mac: 78:0f:77:cc:cc:be
    friendly_name: Outlet2
    type: spmini2
  - platform: broadlink
    friendly_name: Remote
    host: Remote
    mac: 34:EA:34:58:73:5D
    type: rm2_pro_plus
  - platform: broadlink
    friendly_name: Remote2
    host: Remote2
    mac: 78:0F:77:47:AA:8F
    type: rm_mini
  - platform: template
    switches:
      projector:
        friendly_name: Projector
        value_template: "{{ is_state('switch.projector_power', 'on') }}"
        turn_on:
          service: script.turn_on_projector
        turn_off:
          service: script.turn_off_projector

yeelight:
  devices:
    Lamp:
      name: Lamp
      model: bslamp1
    Lamp2:
      name: Lamp2
      model: mono1

light:
  - platform: mqtt
    name: Hallway Spotlight
    state_topic: Hassmart1/relay/0
    command_topic: Hassmart1/relay/0/set
    availability_topic: Hassmart1/status
  - platform: mqtt
    name: Hallway Light
    state_topic: Hassmart1/relay/1
    command_topic: Hassmart1/relay/1/set
    availability_topic: Hassmart1/status
  - platform: mqtt
    name: Diningroom Light2
    state_topic: Hassmart1/relay/2
    command_topic: Hassmart1/relay/2/set
    availability_topic: Hassmart1/status

  - platform: mqtt
    name: Diningroom light
    state_topic: Hassmart2/relay/0
    command_topic: Hassmart2/relay/0/set
    availability_topic: Hassmart2/status
  - platform: mqtt
    name: Passage Spotlight
    state_topic: Hassmart2/relay/1
    command_topic: Hassmart2/relay/1/set
    availability_topic: Hassmart2/status

  - platform: mqtt
    name: Livingroom Light
    state_topic: Hassmart3/relay/0
    command_topic: Hassmart3/relay/0/set
    availability_topic: Hassmart3/status
  - platform: mqtt
    name: Livingroom Spotlight
    state_topic: Hassmart3/relay/1
    command_topic: Hassmart3/relay/1/set
    availability_topic: Hassmart3/status
  - platform: mqtt
    name: Diningroom Spotlight
    state_topic: Hassmart3/relay/2
    command_topic: Hassmart3/relay/2/set
    availability_topic: Hassmart3/status

  - platform: mqtt
    name: Livingroom Light2
    state_topic: Hassmart4/relay/0
    command_topic: Hassmart4/relay/0/set
    availability_topic: Hassmart4/status
  - platform: mqtt
    name: Balcony Light
    state_topic: Hassmart4/relay/1
    command_topic: Hassmart4/relay/1/set
    availability_topic: Hassmart4/status

  - platform: mqtt
    name: Passage Light
    state_topic: Hassmart5/relay/0
    command_topic: Hassmart5/relay/0/set
    availability_topic: Hassmart5/status
  - platform: mqtt
    name: Studyroom Light2
    state_topic: Hassmart5/relay/1
    command_topic: Hassmart5/relay/1/set
    availability_topic: Hassmart5/status
  - platform: mqtt
    name: Studyroom Light3
    state_topic: Hassmart5/relay/2
    command_topic: Hassmart5/relay/2/set
    availability_topic: Hassmart5/status

  - platform: mqtt
    name: Washroom Light
    state_topic: Hassmart6/relay/0
    command_topic: Hassmart6/relay/0/set
    availability_topic: Hassmart6/status

  - platform: mqtt
    name: Passage Backlight
    state_topic: Sonoff1/relay/0
    command_topic: Sonoff1/relay/0/set
    availability_topic: Sonoff1/status
  - platform: mqtt
    name: Passage Light2
    state_topic: Sonoff1/relay/1
    command_topic: Sonoff1/relay/1/set
    availability_topic: Sonoff1/status
  # - platform: mqtt
  #   name: Ceiling Light
  #   state_topic: Sonoff2/relay/0
  #   command_topic: Sonoff2/relay/0/set
  #   availability_topic: Sonoff2/status
  - platform: mqtt
    name: Studyroom Light
    state_topic: Sonoff3/relay/0
    command_topic: Sonoff3/relay/0/set
    availability_topic: Sonoff3/status
  - platform: mqtt
    name: Kidsroom Light
    command_topic: NodeMCU6/irout/set
    availability_topic: NodeMCU6/status
    payload_on: 3526,1658,426,418,426,1292,426,420,426,1288,428,418,426,1290,430,418,426,1290,428,418,426,418,426,416,426,1290,428,416,430,1290,428,1290,428,418,428,1288,428,416,428,418,426,418,428,1288,428,1288,428,1290,428,418,428,1290,428,418,428,1290,428,416,428,1290,428,1290,428,416,428,418,426,418,428,416,428,418,426,416,428,418,426,416,428,416,428,418,426,1292,426,418,428,1290,428,416,428,1292,424,1292,424,1294,424,418,426,1290,426,420,424,418,426,420,424,422,424,1294,424,420,424,420,424,1294,424,420,424,422,422,422,422,1298,422,422,422,1296,422,422,422,1,2,38
    payload_off: 3528,1658,426,418,426,1292,380,462,382,1334,382,464,382,1338,380,462,382,1336,382,462,382,462,382,462,382,1336,382,462,382,1336,380,1336,382,464,382,1338,378,462,384,462,382,464,380,1336,382,1336,382,1336,382,462,382,1334,384,464,382,1336,382,462,382,1336,382,1336,382,464,382,462,382,464,382,464,380,462,382,462,382,464,382,464,380,464,382,464,382,464,380,1338,380,462,382,464,382,462,380,464,380,464,380,464,380,1334,382,464,380,464,380,464,380,464,382,1336,382,464,382,462,382,1334,382,464,382,464,382,464,380,1336,382,1336,382,464,382,1338,380,1,2,38

shell_command:
  turn_off_station: 'ssh root@Station shutdown -h now'
  turn_off_x9300d: 'adb connect x9300d; adb -s x9300d shell reboot -p'

xiaomi_aqara:
  #interface: 192.168.2.40
  gateways:
    - mac: 34CE0090901A
      key: 3ECB50168D7F4AEB

vacuum:
  - platform: xiaomi_miio
    name: Vacuum
    host: Vacuum
    token: 526373684671464d35724d3478667530

fan:
  - platform: xiaomi_miio
    name: Purifier
    host: Purifier
    model: zhimi.airpurifier.m1
    token: FE2D793B34DCE57F32BF50B2E6B00874
  - platform: xiaomi_miio_fan
    name: Fan
    host: Fan
    model: zhimi.fan.v3
    token: 62df0c2f98752f87aa3c6258bf862c9b
  - platform: xiaomi_miio_fan
    name: Fan2
    host: Fan2
    model: zhimi.fan.sa1
    token: 99ddab9b7d5cab866f8def02f348c5c0
  - platform: xiaomi_miio
    name: Fresher
    host: Fresher
    model: zhimi.airfresh.va2
    token: bb1ee8999ee6bc7ce075a424bca664c3
  - platform: xiaomi_miio
    name: Fresher2
    host: Fresher2
    model: zhimi.airfresh.va2
    token: 17487f22521cf634c50b64f5f95c96cb
  - platform: mqtt
    name: Purifier4
    state_topic: NodeMCU4/relay/0
    command_topic: NodeMCU4/relay/0/set
    availability_topic: NodeMCU4/status
    oscillation_state_topic: NodeMCU4/relay/1
    oscillation_command_topic: NodeMCU4/relay/1/set
    speed_state_topic: NodeMCU4/relay/0
    speed_command_topic: NodeMCU4/relay/0/set
    state_value_template: "{% if value == '0' %}OFF{% else %}ON{% endif %}"
    payload_low_speed: '1'
    payload_medium_speed: '2'
    payload_high_speed: '3'
  - platform: mqtt
    name: Purifier5
    state_topic: NodeMCU5/relay/0
    command_topic: NodeMCU5/relay/0/set
    availability_topic: NodeMCU5/status
    oscillation_state_topic: NodeMCU5/relay/1
    oscillation_command_topic: NodeMCU5/relay/1/set
    speed_state_topic: NodeMCU5/relay/0
    speed_command_topic: NodeMCU5/relay/0/set
    state_value_template: "{% if value == '0' %}OFF{% else %}ON{% endif %}"
    payload_low_speed: '1'
    payload_medium_speed: '5'
    payload_high_speed: '4'
  - platform: mqtt
    name: Purifier6
    state_topic: NodeMCU6/relay/0
    command_topic: NodeMCU6/relay/0/set
    availability_topic: NodeMCU6/status
    oscillation_state_topic: NodeMCU6/relay/1
    oscillation_command_topic: NodeMCU6/relay/1/set
    speed_state_topic: NodeMCU6/relay/0
    speed_command_topic: NodeMCU6/relay/0/set
    state_value_template: "{% if value == '0' %}OFF{% else %}ON{% endif %}"
    payload_low_speed: '1'
    payload_medium_speed: '5'
    payload_high_speed: '6'
  - platform: mqtt
    name: Purifier7
    state_topic: NodeMCU7/relay/0
    command_topic: NodeMCU7/relay/0/set
    availability_topic: NodeMCU7/status
    oscillation_state_topic: NodeMCU7/relay/1
    oscillation_command_topic: NodeMCU7/relay/1/set
    speed_state_topic: NodeMCU7/relay/0
    speed_command_topic: NodeMCU7/relay/0/set
    state_value_template: "{% if value == '0' %}OFF{% else %}ON{% endif %}"
    payload_low_speed: '1'
    payload_medium_speed: '5'
    payload_high_speed: '6'
  - platform: smartir
    name: Wall Fan
    device_code: 1044
    controller_data: Remote2

smartir:

climate:
  - platform: saswell
    username: !secret saswell_username
    password: !secret saswell_password
  - platform: modbus2
    name: Daikin
    fan_mode: { registers: [6, 10, 14, 18] }
    fan_modes: { auto: 0, 一级: 1, 二级: 2, 三级: 3, 四级: 4, 五级: 5}
    hvac_mode: { registers: [5, 9, 13, 17] }
    hvac_modes: { 'off': 0, cool: 1, heat: 2, dry: 3, fan_only: 4 }
    hvac_off: { registers: [1, 2, 3, 4], register_type: coil }
    target_temperature: { registers: [4, 8, 12, 16] }
    temperature: { registers: [3, 6, 9, 12], register_type: input, scale: 0.1 }
  - platform: smartir
    name: Mitsubishi
    device_code: 1120
    controller_data: Remote
    temperature_sensor: sensor.fan_temperature
    humidity_sensor: sensor.aircat2_humidity
    #power_sensor: binary_sensor.ac_power

cover:
  - platform: broadlink2
    host: Remote
    mac: 34:EA:34:58:73:5D
    covers:
      studyroom_cover:
        name: Studyroom Cover
        travel_time: 13
        command_open: 'sgD8AJ8wGAwNFxgMGAwYDAwYFwwYDQwYGAsNFw0XDRcYDAwYDBgNFxkMDBgYDBgMDBcNFw0XGQsNFxgMGAwMGAwYDBgXDQwYDBcNFxgMDRcMGAwXGAABIZ4xGQwNFxgMGAwYDAwXGAwYDQwXGAwNFw0XDBgYDAwYDBgMGBgMDBcYDBgMDRcMGAwYGAwMGBgMGAwMFw0XDRcYDA0XDBgMGBgMDBkMFw0XGAABIZ4xFwwNFxgMGAwYDAwYGAwYDAwYGAwMFw0XDRcYDAwYDBgNFxgMDBgYDRgMDBgMFw0YGAsNFxgMGAwMGAwYDBcYDQwYDBcNFxgMDBgMGAwYFwAF3AAAAAAAAAAAAAAAAA=='
        command_stop: 'sgD8AJ4xGAwMGBcMGAwYDAwYGAwYDAwYGAwMGAwZDBcYDAwYDBkLGBgMDBgYDBcNDBgMFw0YFw0MFxgMGAwMGAwYDBgXDQwYFw0MFxgMDRcYDAwYFwABIZ8xGAwMGBcNFw0XDQwXGAwYDQwYFwwNFwwYDBgXDQwYDBgMGBcMDRcYDBgMDBgMGAwYGAwMGBcNFwwNFwwYDBgZDAwYFw0MGBcNDBcYDAwYGAABIJ4xGAwMGBgMGAwXDQwXGAwYDQwYFwwNFwwYDBgYDAwYDRgMGBcNDBcYDBgMDBgMGAwYGAwMGBcNFw0MGAsYDBgYDAwYGAwMGBcNDBcYDAwYGAAF3AAAAAAAAAAAAAAAAA=='
        command_close: 'sgD8AJ0xGAwMGBcNFw0XDQsYGAwYDAwZFwwMGAwYDBgXDQwXDBkMGBcNCxkXDBgMDBkMGAwYGAwMGBcNFw0MGAsZCxgYDQsYDBgXDRcNDBgMGBcNFwABIZ4xFw0MGBcNFwwYDA0YGAwYDAwYGAwMGAwYDBgXDQsYDBgMGBgMDBgXDRcNDBgMGAwYFw0MGBcMGAwMGAwYDBgXDQwYDBgXDRcMDBgMGBgMFwABI50yFw0LGBgMGAwXDQwYFw0XDQwYFw0MGAwYDBcYDAwYDBgMGBgMDBgXDRcNCxkLGAwYGA4MFxgMGAwMGAwYDBgXDQwYDBgXDBgNCxgMGBcNFwAF3AAAAAAAAAAAAAAAAA=='
      # airer:
      #   name: Airer
      #   travel_time: 13
      #   command_open: ''
      #   command_stop: ''
      #   command_close: ''

media_player:
  # - platform: braviatv
  #   host: X9300d
  #   name: X9300d
  - platform: braviatv
    host: X9400e
    name: X9400e
  # - platform: dlna_dmr
  #   url: http://Magic:7300/mdr/desc.xml
  #   name: Magic

panel_iframe:
  dash:
    title: 面板
    icon: mdi:microsoft
    url: /local/dash.html
  nodemcu:
    title: 室内
    icon: mdi:chart-line
    url: !secret nodemcu_url
  nodemcu2:
    title: 阳台
    icon: mdi:chart-areaspline
    url: !secret nodemcu2_url

aligenie:

actuator:

miai:
  miid: !secret miai_miid
  password: !secret miai_password

input_text:
  miai:
    name: MiAI
    initial: 我是小爱
