- alias: 室外空气好
  trigger:
    - platform: numeric_state
      entity_id: sensor.balcony_pm25
      below: 20
      for:
        minutes: 10
  condition:
    - condition: time
      after: '07:00'
      before: '22:00'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d000228a52b
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.balcony_temperature
      above: 10
      below: 30
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.aircat_pm25
          above: 20
        - condition: numeric_state
          entity_id: sensor.fresher_co2
          above: 800
  action:
    - service: zhimsg.miai
      data:
        message: 外面空气很好，可以打开门窗

- alias: 室内空气差
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_pm25
      above: 35
      for:
        minutes: 2
  condition:
    - condition: time
      after: '06:00'
      before: '23:00'
  action:
    - service: zhimsg.miai
      data_template:
        message: '客厅PM2.5为{{ states("sensor.aircat_pm25") }}，空气不好。{% if is_state("binary_sensor.door_window_sensor_158d0001f3d2d1", "on") or is_state("binary_sensor.door_window_sensor_158d0003cf4735", "on") or is_state("binary_sensor.door_window_sensor_158d000228a52b", "on") %}请关好{% if is_state("binary_sensor.door_window_sensor_158d0001f3d2d1", "on") %}厨房门、{% endif %}{% if is_state("binary_sensor.door_window_sensor_158d0003cf4735", "on") %}洗手间门、{% endif %}{% if is_state("binary_sensor.door_window_sensor_158d000228a52b", "on") %}阳台门{% endif %}{% endif %}'
    - delay: 600
    - condition: numeric_state
      entity_id: sensor.aircat_pm25
      above: 40
    - service: automation.trigger
      entity_id: automation.ke_ting_kong_qi_chai

- alias: 环境状况
  trigger:
    - platform: time
      at: '7:30:00'
  action:
    - service: zhimsg.ding
      data_template:
        message: '室内PM2.5为{{ states("sensor.aircat_pm25") }}，温度为{{ states("sensor.aircat_temperature") }}，CO2为客厅{{ states("sensor.fresher_co2") }}/主卧{{ states("sensor.fresher2_co2") }}/儿童房{{ states("sensor.nodemcu7_co2") }}。室外PM2.5为{{ states("sensor.balcony_pm25") }}，温度为{{ states("sensor.balcony_temperature") }}；{{ state_attr("weather.caiyun", "attribution") }}'
