# 客厅二氧化碳变化
- alias: CO2 Changed @Livingroom
  trigger:
    - platform: state
      entity_id: sensor.fresher_co2
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fresher_co2
        sensor_values: [500, 680, 730]
        entity_id: fan.fresher
        entity_attr: speed
        entity_values: [Auto, Middle, Strong]

# 主卧二氧化碳变化
- alias: CO2 Changed @Bedroom
  trigger:
    - platform: state
      entity_id: sensor.purifier7_co2
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier7_co2
        sensor_values: [500, 680, 730]
        alt_sensor_values: [500, 750, 1000]
        entity_id: fan.fresher2
        entity_attr: speed
        entity_values: [Auto, Middle, Strong]
