- alias: 客厅新风机调节
  trigger:
    - platform: state
      entity_id: sensor.fresher_co2
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fresher_co2
        sensor_values: [500, 580, 680, 730]
        entity_id: fan.ke_ting_xin_feng_ji
        entity_attr: speed
        entity_values: [Silent, Low, Middle, Strong]
        condition_attr: mode
        condition_values: [silent, low, middle, strong]

- alias: 主卧新风机调节
  trigger:
    - platform: state
      entity_id: sensor.zhu_wo_er_yang_hua_tan
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.zhu_wo_er_yang_hua_tan
        sensor_values: [500, 650, 750, 900]
        alt_sensor_values: [500, 720, 900, 1500]
        entity_id: fan.zhu_wo_xin_feng_ji
        entity_attr: speed
        entity_values: [Silent, Low, Middle, Strong]
        condition_attr: mode
        condition_values: [silent, low, middle, strong]
