- alias: 客厅新风机调节
  trigger:
    - platform: state
      entity_id: sensor.fresher_co2
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fresher_co2
        sensor_values: [500, 580, 680, 730]
        entity_id: fan.fresher
        entity_attr: speed
        entity_values: [Silent, Low, Middle, Strong]
        condition_attr: mode
        condition_values: [silent, low, middle, strong]

- alias: 主卧新风机调节
  trigger:
    - platform: state
      entity_id: sensor.fresher2_co2
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fresher2_co2
        sensor_values: [500, 650, 750, 900]
        alt_sensor_values: [500, 720, 900, 1500]
        entity_id: fan.fresher2
        entity_attr: speed
        entity_values: [Silent, Low, Middle, Strong]
        condition_attr: mode
        condition_values: [silent, low, middle, strong]
