- alias: 魔方翻转九十度
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: flip90
  action:
    - service: zhimsg.ding
      data:
        message: 魔方翻转九十度

- alias: 魔方翻转一百八十度
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: flip180
  action:
    - service: zhimsg.ding
      data:
        message: 魔方翻转一百八十度

- alias: 魔方移动
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: move
  action:
    - service: zhimsg.ding
      data:
        message: 魔方移动

- alias: 魔方敲击两下
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: tap_twice
  action:
    - service: zhimsg.ding
      data:
        message: 魔方敲击两下

- alias: 魔方摇一摇-召唤神龙爸爸
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: shake_air
  action:
    - service: zhimsg.ding
      data:
        message: 召唤神龙爸爸
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34CE0090901A
        ringtone_id: 10016
        ringtone_vol: 60

- alias: 魔方摇摆
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: swing
  action:
    - service: zhimsg.ding
      data:
        message: 魔方摇摆

- alias: 魔方警告
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: alert
  action:
    - service: zhimsg.ding
      data:
        message: 魔方警告

- alias: 魔方下落
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: free_fall
  action:
    - service: zhimsg.ding
      data:
        message: 魔方下落

- alias: 魔方旋转
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: rotate
  action:
    - service: zhimsg.ding
      data:
        message: 魔方旋转
