- alias: 餐厅除湿机开
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_humidity
      above: 74
      for:
        minutes: 10
  action:
    - service: switch.turn_on
      entity_id: switch.outlet

- alias: 餐厅除湿机关
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_humidity
      below: 70
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.outlet

- alias: 儿童房除湿机开
  trigger:
    - platform: numeric_state
      entity_id: sensor.nodemcu7_humidity
      above: 75
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
  action:
    - service: switch.turn_on
      entity_id: switch.outlet2

- alias: 儿童房除湿机关
  trigger:
    - platform: numeric_state
      entity_id: sensor.nodemcu7_humidity
      below: 72
      for:
        minutes: 10
    - platform: time
      at: '20:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.outlet2

- alias: 餐厅加湿器开
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_humidity
      below: 56
      for:
        minutes: 10
  action:
    - service: automation.turn_off
      entity_id: automation.diao_jie_jing_hua_qi_can_ting
    - service: fan.turn_on
      entity_id: fan.purifier5
    - service: fan.oscillate
      data:
        entity_id: fan.purifier5
        oscillating: true
    - service: fan.set_speed
      data:
        entity_id: fan.purifier5
        speed: low

- alias: 餐厅加湿器关
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_humidity
      above: 60
      for:
        minutes: 10
  action:
    - service: fan.oscillate
      data:
        entity_id: fan.purifier5
        oscillating: false
    - service: automation.turn_on
      entity_id: automation.diao_jie_jing_hua_qi_can_ting

- alias: 主卧加湿器开
  trigger:
    - platform: numeric_state
      entity_id: sensor.fresher2_humidity
      below: 58
      for:
        minutes: 10
  action:
    - service: automation.turn_off
      entity_id: automation.diao_jie_jing_hua_qi_zhu_wo
    - service: fan.turn_on
      entity_id: fan.purifier6
    - service: fan.oscillate
      data:
        entity_id: fan.purifier6
        oscillating: true
    - service: fan.set_speed
      data:
        entity_id: fan.purifier6
        speed: low

- alias: 主卧加湿器关
  trigger:
    - platform: numeric_state
      entity_id: sensor.fresher2_humidity
      above: 62
      for:
        minutes: 10
  action:
    - service: fan.oscillate
      data:
        entity_id: fan.purifier6
        oscillating: false
    - service: automation.turn_on
      entity_id: automation.diao_jie_jing_hua_qi_zhu_wo

- alias: 儿童房加湿器开
  trigger:
    - platform: numeric_state
      entity_id: sensor.nodemcu7_humidity
      below: 56
      for:
        minutes: 10
  action:
    - service: automation.turn_off
      entity_id: automation.diao_jie_jing_hua_qi_er_tong_fang
    - service: fan.turn_on
      entity_id: fan.purifier7
    - service: fan.oscillate
      data:
        entity_id: fan.purifier7
        oscillating: true
    - service: fan.set_speed
      data:
        entity_id: fan.purifier7
        speed: low
        
- alias: 儿童房加湿器关
  trigger:
    - platform: numeric_state
      entity_id: sensor.nodemcu7_humidity
      above: 60
      for:
        minutes: 10
  action:
    - service: fan.oscillate
      data:
        entity_id: fan.purifier7
        oscillating: false
    - service: automation.turn_on
      entity_id: automation.diao_jie_jing_hua_qi_er_tong_fang
