# 餐厅湿度过高
- alias: Humidity High @Diningroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_humidity
      above: 74
      for:
        minutes: 10
  action:
    - service: switch.turn_on
      entity_id: switch.outlet

# 餐厅湿度正常
- alias: Humidity Normal @Diningroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_humidity
      below: 70
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.outlet

# 卧室湿度过高
- alias: Humidity High @Bedroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.purifier7_humidity
      above: 75
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
  action:
    - service: switch.turn_on
      entity_id: switch.outlet2

# 卧室湿度正常
- alias: Humidity Normal @Bedroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.purifier7_humidity
      below: 72
      for:
        minutes: 10
    - platform: time
      at: '20:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.outlet2

# 餐厅湿度过低
# - alias: Humidity Low @Diningroom
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.purifier5_humidity
#       below: 52
#       for:
#         minutes: 10
#   action:
#     - service: fan.turn_on
#       entity_id: fan.purifier5
#     - service: fan.oscillate
#       data:
#         entity_id: fan.purifier5
#         oscillating: true

# 主卧湿度过低
# - alias: Humidity Low @Bedroom
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.fresher2_humidity
#       below: 52
#       for:
#         minutes: 10
#   action:
#     - service: fan.turn_on
#       entity_id: fan.purifier7
#     - service: fan.oscillate
#       data:
#         entity_id: fan.purifier7
#         oscillating: true

# 儿童房湿度过低
# - alias: Humidity Low @Kidsroom
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.purifier7_humidity
#       below: 52
#       for:
#         minutes: 10
#   action:
#     - service: fan.turn_on
#       entity_id: fan.purifier7
#     - service: fan.oscillate
#       data:
#         entity_id: fan.purifier7
#         oscillating: true
