# 餐厅湿度过高
- alias: Diningroom Humidity High
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_humidity
      above: 74
      for:
        minutes: 10
  action:
    - service: switch.turn_on
      entity_id: switch.outlet

# 餐厅湿度正常
- alias: Diningroom Humidity Normal
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_humidity
      below: 70
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.outlet

# 卧室湿度过高
- alias: Bedroom Humidity High
  trigger:
    - platform: numeric_state
      entity_id: sensor.purifier6_humidity
      above: 74
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
  action:
    - service: switch.turn_on
      entity_id: switch.outlet2

# 卧室湿度正常
- alias: Bedroom Humidity Normal
  trigger:
    - platform: numeric_state
      entity_id: sensor.purifier6_humidity
      below: 70
      for:
        minutes: 10
    # - platform: time
    #   at: '08:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.outlet2

# 餐厅湿度过低
# - alias: Diningroom Humidity Low
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.purifier5_humidity
#       below: 52
#       for:
#         minutes: 10
#   action:
#     - service: fan.turn_on
#       entity_id: fan.purifier5
#     - service: fan.oscillate
#       data:
#         entity_id: fan.purifier5
#         oscillating: true

# 主卧湿度过低
# - alias: Bedroom Humidity Low
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.purifier7_humidity
#       below: 52
#       for:
#         minutes: 10
#   action:
#     - service: fan.turn_on
#       entity_id: fan.purifier7
#     - service: fan.oscillate
#       data:
#         entity_id: fan.purifier7
#         oscillating: true

# 儿童房湿度过低
# - alias: Kids Humidity Low
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.purifier6_humidity
#       below: 52
#       for:
#         minutes: 10
#   action:
#     - service: fan.turn_on
#       entity_id: fan.purifier6
#     - service: fan.oscillate
#       data:
#         entity_id: fan.purifier6
#         oscillating: true
