- alias: 小爱音播报
  trigger:
    - platform: state
      entity_id: input_text.miai
  action:
    - condition: template
      value_template: '{{ states("input_text.miai") != "unknown" and states("input_text.miai") != "" }}'
    - service: zhimsg.miai
      data_template:
        message: '{{ states("input_text.miai") }}'
