# 
- alias: 过道背景灯感应
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      from: 'off'
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.illumination_34ce0090901a
          below: 100
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.illumination_34ce0090901a
            below: 300
          - condition: state
            entity_id: sun.sun
            state: above_horizon
  action:
    - service: light.turn_on
      entity_id: light.passage_backlight
    - wait_template: '{{ is_state("binary_sensor.motion_sensor_158d0001d66ce9", "off") }}'
    - service: light.turn_off
      entity_id: light.passage_backlight

#
- alias: 餐厅筒灯同步
  trigger:
    - platform: state
      entity_id: light.dining_spotlight2, light.dining_spotlight
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.dining_spotlight2" %}light.dining_spotlight{% else %}light.dining_spotlight2{% endif %}'

#
- alias: 客厅筒灯同步
  trigger:
    - platform: state
      entity_id: light.living_spotlight2, light.living_spotlight
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.living_spotlight2" %}light.living_spotlight{% else %}light.living_spotlight2{% endif %}'
