# 
- alias: 过道背景灯感应
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      from: 'off'
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.illumination_34ce0090901a
      below: 300
  action:
    - service: light.turn_on
      entity_id: light.passage_backlight
    - wait_template: '{{ is_state("binary_sensor.motion_sensor_158d0001d66ce9", "off") }}'
    - service: light.turn_off
      entity_id: light.passage_backlight

# - alias: 过道灯同步
#   trigger:
#     - platform: state
#       entity_id: light.passage_light2, light.passage_light
#   action:
#     - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
#       data_template:
#         entity_id: '{% if trigger.entity_id == "light.passage_light2" %}light.passage_light{% else %}light.passage_light2{% endif %}'
