# 餐厅颗粒物变化
- alias: PM25 Changed @Diningroom
  trigger:
    - platform: state
      entity_id: sensor.aircat_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.aircat_pm25
        sensor_values: [10, 20, 50]
        entity_id: fan.purifier5
        entity_attr: speed
        entity_values: [low, medium, high]

# 主卧颗粒物变化
- alias: PM25 Changed @Bedroom
  trigger:
    - platform: state
      entity_id: sensor.purifier7_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier7_pm25
        sensor_values: [5, 20, 50]
        entity_id: fan.purifier7
        entity_attr: speed
        entity_values: [low, medium, high]

# 次卧颗粒物变化
- alias: PM25 Changed @Parentsroom
  trigger:
    - platform: state
      entity_id: sensor.purifier_pm25
  action:
    - service: fan.set_speed
      data:
      #data_template:
        entity_id: fan.purifier
        speed: favorite
        #speed: '{% if (states("sensor.purifier_pm25") | int > 35) and is_state("switch.projector", "off") %}favorite{% else %}auto{% endif %}'
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier_pm25
        sensor_values: [15, 20, 35, 60, 80]
        sensor_values_alt: [20, 30, 50, 80, 100]
        entity_id: fan.purifier6
        entity_attr: favorite_level
        service: xiaomi_miio_set_favorite_level
        service_attr: level
        entity_values: [2, 3, 6, 9, 10]

# 儿童房颗粒物变化
- alias: PM25 Changed @Kidsroom
  trigger:
    - platform: state
      entity_id: sensor.purifier6_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier6_pm25
        sensor_values: [5, 20, 50]
        entity_id: fan.purifier6
        entity_attr: speed
        entity_values: [low, medium, high]

# 书房颗粒物变化
- alias: PM25 Changed @Studyroom
  initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.aircat2_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.aircat2_pm25
        sensor_values: [10, 20, 50]
        entity_id: fan.purifier4
        entity_attr: speed
        entity_values: [low, medium, high]
