- alias: 餐厅净化器调节
  trigger:
    - platform: state
      entity_id: sensor.aircat_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.aircat_pm25
        sensor_values: [10, 20, 50]
        entity_id: fan.purifier5
        entity_attr: speed
        entity_values: [low, medium, high]

- alias: 主卧净化器调节
  trigger:
    - platform: state
      entity_id: sensor.fresher2_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fresher2_pm25
        sensor_values: [7, 15, 40]
        alt_sensor_values: [5, 20, 40]
        entity_id: fan.purifier6
        entity_attr: speed
        entity_values: [low, medium, high]

- alias: 次卧净化器调节
  trigger:
    - platform: state
      entity_id: sensor.purifier_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier_pm25
        sensor_values: [15, 40, 60, 80]
        alt_sensor_values: [20, 50, 80, 100]
        entity_id: fan.purifier
        entity_attr: favorite_level
        service: xiaomi_miio_set_favorite_level
        service_attr: level
        entity_values: [3, 6, 9, 10]
        delay: 300
        condition_attr: mode
        condition_values: [favorite]

- alias: 儿童房净化器调节
  trigger:
    - platform: state
      entity_id: sensor.nodemcu7_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.nodemcu7_pm25
        sensor_values: [10, 20, 50]
        alt_sensor_values: [7, 30, 50]
        entity_id: fan.purifier7
        entity_attr: speed
        entity_values: [low, medium, high]

- alias: 书房净化器调节
  initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.aircat2_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.aircat2_pm25
        sensor_values: [10, 20, 50]
        alt_sensor_values: [10, 30, 50]
        entity_id: fan.purifier4
        entity_attr: speed
        entity_values: [low, medium, high]
