- alias: 餐厅净化器调节
  trigger:
    - platform: state
      entity_id: sensor.aircat_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.aircat_pm25
        sensor_values: [10, 20, 50]
        entity_id: fan.purifier5
        entity_attr: speed
        entity_values: [low, medium, high]
        condition_attr: oscillating
        condition_values: [false]

- alias: 主卧净化器调节
  trigger:
    - platform: state
      entity_id: sensor.zhu_wo_ke_li_wu
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.zhu_wo_ke_li_wu
        sensor_values: [7, 15, 40]
        alt_sensor_values: [5, 20, 40]
        entity_id: fan.purifier6
        entity_attr: speed
        entity_values: [low, medium, high]
        condition_attr: oscillating
        condition_values: [false]

- alias: 次卧净化器调节
  trigger:
    - platform: state
      entity_id: sensor.ci_wo_ke_li_wu
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.ci_wo_ke_li_wu
        sensor_values: [12, 15, 20, 30, 40, 50, 60, 70, 80, 90]
        alt_sensor_values: [15, 20, 30, 40, 50, 60, 70, 80, 90, 100]
        entity_id: fan.purifier
        entity_attr: favorite_level
        service: xiaomi_miio.fan_set_favorite_level
        service_attr: level
        entity_values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        condition_attr: mode
        condition_values: [idle, favorite]

- alias: 儿童房净化器调节
  trigger:
    - platform: state
      entity_id: sensor.er_tong_fang_ke_li_wu
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.er_tong_fang_ke_li_wu
        sensor_values: [10, 20, 50]
        alt_sensor_values: [7, 30, 50]
        entity_id: fan.purifier7
        entity_attr: speed
        entity_values: [low, medium, high]
        condition_attr: oscillating
        condition_values: [false]

- alias: 书房净化器调节
  initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.aircat2_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.aircat2_pm25
        sensor_values: [10, 20, 50]
        alt_sensor_values: [10, 30, 50]
        entity_id: fan.purifier4
        entity_attr: speed
        entity_values: [low, medium, high]
