- alias: 睡眠准备
  trigger:
    - platform: time
      at: '20:30:00'
  action:
    - service: cover.close_cover
      entity_id: cover.study_cover
    - service: xiaomi_miio.fan_set_led_brightness
      data:
        entity_id: fan.fresher
        brightness: 2
    - service: xiaomi_miio.fan_set_led_brightness
      data:
        entity_id: fan.fresher2
        brightness: 2
    # - service: fan.set_speed
    #   data:
    #     entity_id: fan.purifier
    #     speed: Silent
    - service: zhimsg.miai
      data:
        volume: 30
    - service: climate.set_temperature
      data:
        entity_id: climate.daikin3
        temperature: 25
        #hvac_mode: cool
    - service: climate.set_temperature
      data:
        entity_id: climate.daikin4
        temperature: 25
        #hvac_mode: cool

# - alias: 睡眠开始
#   trigger:
#     - platform: time
#       at: '21:30:00'
#   action:

# 进入深睡
- alias: 睡眠深入
  trigger:
    - platform: time
      at: '00:00:01'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.daikin3
        temperature: 26
        #hvac_mode: cool
    - service: climate.set_temperature
      data:
        entity_id: climate.daikin4
        temperature: 26
        #hvac_mode: cool

- alias: 睡眠结束
  trigger:
    - platform: time
      at: '07:30:00'
  action:
    - service: cover.open_cover
      entity_id: cover.study_cover
    - service: xiaomi_miio.fan_set_led_brightness
      data:
        entity_id: fan.fresher
        brightness: 0
    - service: xiaomi_miio.fan_set_led_brightness
      data:
        entity_id: fan.fresher2
        brightness: 0
    - service: zhimsg.miai
      data:
        volume: 60
    - service: climate.set_fan_mode
      data:
        entity_id: climate.daikin3
        fan_mode: 自动
    - service: climate.set_fan_mode
      data:
        entity_id: climate.daikin4
        fan_mode: 自动
    - service: climate.turn_off
      entity_id: climate.daikin3
    - service: climate.turn_off
      entity_id: climate.daikin4
    - service: climate.turn_off
      entity_id: climate.mitsubishi
    - service: fan.turn_off
      entity_id: fan.fan
    - service: fan.turn_off
      entity_id: fan.fan2
