#过道无线开关单击
- alias: Switch Clicked @Passage
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: single
  action:
    - service: miai.say
      data_template:
        message: '阳台PM2.5为{{ states("sensor.balcony_pm25") }}，餐厅PM2.5为{{ states("sensor.aircat_pm25") }}，主卧PM2.5为{{ states("sensor.purifier7_pm25") }}。客厅二氧化碳浓度为{{ states("sensor.fresher_co2") }}，主卧二氧化碳浓度为{{ states("sensor.purifier7_co2") }}，儿童房二氧化碳浓度为{{ states("sensor.purifier6_co2") }}'

# 过道无线开关双击
- alias: Switch DbClicked @Passage
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: double
  action:
    - service: miai.say
      data:
        message: 晾衣机将于今晚定时开启烘干功能

# 过道无线开关长按
- alias: Switch Pressed @Passage
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: long_click_press
  action:
    - service: automation.toggle
      entity_id: automation.passage_light_on_day
    - service: automation.toggle
      entity_id: automation.passage_light_off_day
    - service: automation.toggle
      entity_id: automation.passage_light_off_brighten
    - service: automation.toggle
      entity_id: automation.passage_light_on_night
    - service: automation.toggle
      entity_id: automation.passage_light_off_night
    - service: automation.toggle
      entity_id: automation.passage_backlight_reaction
    - service: miai.say
      data_template:
        message: '过道灯自动感应功能已{% if is_state("automation.passage_backlight_reaction", "on") %}启用{% else %}暂停，所有灯光将在10秒后关闭{% endif %}'
    - delay: '00:00:10'
    - condition: state
      entity_id: automation.passage_backlight_reaction
      state: 'off'
    - service: automation.turn_on
      entity_id: automation.passage_light_reaction_enabler
    - service: homeassistant.turn_off
      entity_id: group.all_lights

# 书房无线开关单击
- alias: Switch Clicked @Studyroom
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201a73f
        click_type: single
  action:
    - service: mqtt.publish
      data:
        topic: NodeMCU3/relay/0/set
        payload: toggle

# 书房无线开关双击
- alias: Switch DbClicked @Studyroom
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201a73f
        click_type: double
  action:
    - service: miai.say
      data_template:
        message: '正在{% if is_state("switch.projector", "on") %}关闭{% else %}打开{% endif %}投影仪'
    - service: switch.toggle
      entity_id: switch.projector

# 书房无线开关长按
- alias: Switch Pressed @Studyroom
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201a73f
        click_type: long_click_press
  action:
    - service: mqtt.publish
      data:
        topic: NodeMCU3/relay/0/set
        payload: 'off'
