- alias: 过道按钮单击—播报空气
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: single
  action:
    - service: zhimsg.miai
      data_template:
        message: '阳台PM2.5为{{ states("sensor.yang_tai_ke_li_wu") }}，餐厅PM2.5为{{ states("sensor.can_ting_ke_li_wu") }}，主卧PM2.5为{{ states("sensor.zhu_wo_ke_li_wu") }}。客厅二氧化碳浓度为{{ states("sensor.ke_ting_er_yang_hua_tan") }}，主卧二氧化碳浓度为{{ states("sensor.zhu_wo_er_yang_hua_tan") }}，儿童房二氧化碳浓度为{{ states("sensor.er_tong_fang_er_yang_hua_tan") }}'

- alias: 过道按钮双击—预约洗衣
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: double
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.washer
        speed: 预约洗衣
    - service: fan.turn_on
      entity_id: fan.washer
    - service: zhimsg.miai
      data:
        message: 洗衣机已预约早晨洗衣

- alias: 过道按钮长按—开关过道灯感应
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: long_click_press
  action:
    - service: automation.toggle
      entity_id: automation.guo_dao_deng_bai_tian_kai
    - service: automation.toggle
      entity_id: automation.guo_dao_deng_wan_shang_kai
    - service: automation.toggle
      entity_id: automation.guo_dao_bei_jing_deng_gan_ying
    - service: zhimsg.miai
      data_template:
        message: '过道灯自动感应功能已{% if is_state("automation.guo_dao_bei_jing_deng_gan_ying", "on") %}启用{% else %}暂停，所有灯光将在10秒后关闭{% endif %}'
    - delay: '00:00:10'
    - condition: state
      entity_id: automation.guo_dao_bei_jing_deng_gan_ying
      state: 'off'
    - service: automation.turn_on
      entity_id: automation.guo_dao_deng_gan_ying_zhong_qi
    - service: light.turn_off
      entity_id: all

- alias: 过道灯感应重启
  initial_state: false
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    - service: automation.turn_on
      entity_id: automation.guo_dao_deng_bai_tian_kai
    - service: automation.turn_on
      entity_id: automation.guo_dao_deng_wan_shang_kai
    - service: automation.turn_on
      entity_id: automation.guo_dao_bei_jing_deng_gan_ying
    - service: zhimsg.miai
      data:
        message: 过道灯自动感应功能已重新启用
    - delay: '00:00:10'
    - service: automation.turn_off
      entity_id: automation.guo_dao_deng_gan_ying_zhong_qi
