# 餐厅灯开关同步
- alias: Diningroom Light Sync
  trigger:
    - platform: state
      entity_id: light.diningroom_light2, light.diningroom_light
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.diningroom_light2" %}light.diningroom_light{% else %}light.diningroom_light2{% endif %}'

# 客厅灯开关同步
- alias: Parlor Light Sync
  trigger:
    - platform: state
      entity_id: light.parlor_light2, light.parlor_light
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.parlor_light2" %}light.parlor_light{% else %}light.parlor_light2{% endif %}'

# 过道灯开关同步
- alias: Passage Light Sync
  trigger:
    - platform: state
      entity_id: light.passage_light2, light.passage_light
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.passage_light2" %}light.passage_light{% else %}light.passage_light2{% endif %}'

# 书房灯开关同步
- alias: Study Light Sync
  trigger:
    - platform: state
      entity_id: light.study_light2, light.study_light3, light.study_light
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.study_light2" %}light.study_light,light.study_light3{% elif trigger.entity_id == "light.study_light3" %}light.study_light,light.study_light2{% else %}light.study_light2,light.study_light3{% endif %}'
