# 主卧空调温度变化
- alias: Temperature Changed @Bedroom
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.fresher2_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fresher2_temperature
        sensor_values: [28, 29.3, 30, 31, 32]
        alt_sensor_values: [28.3, 29.5, 30, 31, 32]
        alt_time_range: [2, 7]
        entity_id: climate.daikin3
        entity_attr: fan_mode
        entity_values: [一档, 二档, 三档, 四档, 五档]

# 儿童房空调温度变化
- alias: Temperature Changed @Kidsroom
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.purifier7_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier7_temperature
        sensor_values: [22, 22.5, 23, 24, 25]
        alt_sensor_values: [23, 23.5, 24,25, 26]
        alt_time_range: [2, 7]
        entity_id: climate.daikin4
        entity_attr: fan_mode
        entity_values: [一档, 二档, 三档, 四档, 五档]

# 书房空调温度变化
- alias: Temperature Changed @Studyroom
  trigger:
    - platform: time
      at: '21:00:01'
    - platform: state
      entity_id: sensor.fan_temperature
  condition:
    - condition: time
      after: '20:30'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fan_temperature
        sensor_values: [27.5, 28.5, 32, 34]
        alt_sensor_values: [28.5, 29, 32, 34]
        alt_time_range: [2, 7]
        entity_id: climate.mitsubishi
        entity_attr: fan_mode
        entity_values: [low, mid, high, highest]

# 书房风扇温度变化
- alias: Temperature Changed @Fan
  trigger:
    - platform: time
      at: '21:00:01'
    - platform: state
      entity_id: sensor.fan_temperature
  condition:
    - condition: time
      after: '20:30'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fan_temperature
        sensor_values: [24, 26, 30, 32]
        alt_sensor_values: [25, 28, 32, 34]
        alt_time_range: [2, 7]
        entity_id: fan.fan
        entity_attr: speed_level
        #service: set_speed
        service_attr: speed
        entity_values: [Level 1, Level 2, Level 3, Level 4]

# 儿童房风扇温度变化
- alias: Temperature Changed @Fan2
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.purifier7_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier7_temperature
        sensor_values: [20, 21.5, 23, 24]
        alt_sensor_values: [21, 22, 23, 24]
        alt_time_range: [2, 7]
        entity_id: fan.fan2
        entity_attr: speed_level
        #service: set_speed
        service_attr: speed
        entity_values: [Level 1, Level 2, Level 3, Level 4]
