# 主卧空调温度变化
- alias: Temperature Changed @Bedroom
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.purifier7_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:00'
  action:
    - service: actuator.actuate
      data:
        sensor_id: climate.daikin3
        sensor_attr: current_temperature
        sensor_values: [24, 26, 28, 30, 32]
        alt_sensor_values: [25, 27, 29, 31, 33]
        alt_time_range: [2, 6]
        entity_id: climate.daikin4
        entity_attr: fan_mode
        entity_values: [一级, 二级, 三级, 四级, 五级]

# 儿童房空调温度变化
- alias: Temperature Changed @Kidsroom
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.purifier6_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:00'
  action:
    - service: actuator.actuate
      data:
        sensor_id: climate.daikin4
        sensor_attr: current_temperature
        sensor_values: [24, 26, 28, 30, 32]
        alt_sensor_values: [25, 27, 29, 31, 33]
        alt_time_range: [2, 6]
        entity_id: climate.daikin4
        entity_attr: fan_mode
        entity_values: [一级, 二级, 三级, 四级, 五级]

# 儿童房风扇温度变化
- alias: Temperature Changed @Fan
  trigger:
    - platform: time
      at: '21:00:01'
    - platform: state
      entity_id: sensor.fan_temperature
  condition:
    - condition: time
      after: '20:30'
      before: '07:00'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fan_temperature
        sensor_values: [23, 26, 30, 32]
        alt_sensor_values: [25, 28, 32, 34]
        alt_time_range: [2, 6]
        entity_id: fan.fan
        entity_attr: speed_level
        #service: set_speed
        service_attr: speed
        entity_values: [Level 1, Level 2, Level 3, Level 4]

# 儿童房风扇温度变化
- alias: Temperature Changed @Fan2
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.purifier6_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:00'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier6_temperature
        sensor_values: [23, 26, 30, 32]
        alt_sensor_values: [25, 28, 32, 34]
        alt_time_range: [2, 6]
        entity_id: fan.fan2
        entity_attr: speed_level
        #service: set_speed
        service_attr: speed
        entity_values: [Level 1, Level 2, Level 3, Level 4]
