# 主卧温度高
# - alias: Temperature High @Bedroom
#   trigger:
#     - platform: numeric_state
#       entity_id: climate.daikin3
#       value_template: '{{ state.attributes.current_temperature }}'
#       above: 28
#       for:
#         minutes: 10
#   condition:
#     - condition: time
#       after: '20:00'
#       before: '08:00'
#   action:
#     - service: climate.turn_on
#       entity_id: climate.daikin3

# # 主卧温度低
# - alias: Temperature Low @Bedroom
#   trigger:
#     - platform: numeric_state
#       entity_id: climate.daikin3
#       value_template: '{{ state.attributes.current_temperature }}'
#       below: 25
#       for:
#         minutes: 10
#   action:
#     - service: climate.turn_off
#       entity_id: climate.daikin3

# 儿童房温度高
# - alias: Temperature High @Kidsroom
#   trigger:
#     - platform: numeric_state
#       entity_id: climate.daikin4
#       value_template: '{{ state.attributes.current_temperature }}'
#       above: 28
#       for:
#         minutes: 10
#   condition:
#     - condition: time
#       after: '20:00'
#       before: '08:00'
#   action:
#     - service: climate.turn_on
#       entity_id: climate.daikin4

# # 儿童房温度低
# - alias: Temperature Low @Kidsroom
#   trigger:
#     - platform: numeric_state
#       entity_id: climate.daikin4
#       value_template: '{{ state.attributes.current_temperature }}'
#       below: 25
#       for:
#         minutes: 10
#   action:
#     - service: climate.turn_off
#       entity_id: climate.daikin4

# 主卧空调温度变化
- alias: Temperature Changed @Bedroom
  trigger:
    - platform: time
      at: '20:00:01'
    - platform: numeric_state
      entity_id: climate.daikin3
      value_template: '{{ state.attributes.current_temperature }}'
      above: 32 # 升至高档
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: climate.daikin3
      value_template: '{{ state.attributes.current_temperature }}'
      above: 30 # 升至中档
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: climate.daikin3
      value_template: '{{ state.attributes.current_temperature }}'
      above: 28 # 升至低档
      for:
        minutes: 6
    - platform: numeric_state
      entity_id: climate.daikin3
      value_template: '{{ state.attributes.current_temperature }}'
      below: 31 # 降至中档
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: climate.daikin3
      value_template: '{{ state.attributes.current_temperature }}'
      below: 29 # 降至低档
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: climate.daikin3
      value_template: '{{ state.attributes.current_temperature }}'
      below: 25 # 降至关机
      for:
        minutes: 6
  condition:
    - condition: time
      after: '20:00'
      before: '08:00'
  action:
    - service_template: '{% if (state_attr("climate.daikin3", "current_temperature") | float > 25) %}climate.turn_on{% else %}climate.turn_off{% endif %}'
      entity_id: climate.daikin3
    - condition: numeric_state
      entity_id: climate.daikin3
      value_template: '{{ state.attributes.current_temperature }}'
      above: 25
    - service: climate.set_temperature
      data_template:
        entity_id: climate.daikin3
        temperature: '{% if (state_attr("climate.daikin3", "current_temperature") | float > 32) %}23{% elif (state_attr("climate.daikin3", "current_temperature") | float > 30) %}24{% else %}25{% endif %}'
        operation_mode: cool
    - service: climate.set_fan_mode
      data_template:
        entity_id: climate.daikin3
        fan_mode: '{% if (state_attr("climate.daikin3", "current_temperature") | float > 32) %}三级{% elif (state_attr("climate.daikin3", "current_temperature") | float > 30) %}二级{% else %}一级{% endif %}'
    - delay: 1
    - service: logbook.log
      data_template:
        name: '{{ state_attr("climate.daikin3", "friendly_name") }}={{ state_attr("climate.daikin3", "current_temperature") }}'
        message: '{{ state_attr("climate.daikin3", "friendly_name") }}⇒{{ state_attr("climate.daikin3", "fan_mode") }}'

# 儿童房空调温度变化
- alias: Temperature Changed @Kidsroom
  trigger:
    - platform: time
      at: '20:00:01'
    - platform: numeric_state
      entity_id: climate.daikin4
      value_template: '{{ state.attributes.current_temperature }}'
      above: 32 # 升至高档
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: climate.daikin4
      value_template: '{{ state.attributes.current_temperature }}'
      above: 30 # 升至中档
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: climate.daikin4
      value_template: '{{ state.attributes.current_temperature }}'
      above: 28 # 升至低档
      for:
        minutes: 6
    - platform: numeric_state
      entity_id: climate.daikin4
      value_template: '{{ state.attributes.current_temperature }}'
      below: 31 # 降至中档
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: climate.daikin4
      value_template: '{{ state.attributes.current_temperature }}'
      below: 29 # 降至低档
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: climate.daikin4
      value_template: '{{ state.attributes.current_temperature }}'
      below: 25 # 降至关机
      for:
        minutes: 6
  condition:
    - condition: time
      after: '20:00'
      before: '08:00'
  action:
    - service_template: '{% if (state_attr("climate.daikin4", "current_temperature") | float > 25) %}climate.turn_on{% else %}climate.turn_off{% endif %}'
      entity_id: climate.daikin4
    - condition: numeric_state
      entity_id: climate.daikin4
      value_template: '{{ state.attributes.current_temperature }}'
      above: 25
    - service: climate.set_temperature
      data_template:
        entity_id: climate.daikin4
        temperature: '{% if (state_attr("climate.daikin4", "current_temperature") | float > 32) %}23{% elif (state_attr("climate.daikin4", "current_temperature") | float > 30) %}24{% else %}25{% endif %}'
        operation_mode: cool
    - service: climate.set_fan_mode
      data_template:
        entity_id: climate.daikin4
        fan_mode: '{% if (state_attr("climate.daikin4", "current_temperature") | float > 32) %}三级{% elif (state_attr("climate.daikin4", "current_temperature") | float > 30) %}二级{% else %}一级{% endif %}'
    - delay: 1
    - service: logbook.log
      data_template:
        name: '{{ state_attr("climate.daikin4", "friendly_name") }}={{ state_attr("climate.daikin4", "current_temperature") }}'
        message: '{{ state_attr("climate.daikin4", "friendly_name") }}⇒{{ state_attr("climate.daikin4", "fan_mode") }}'

# 儿童房风扇温度变化
- alias: Temperature Changed @Fan
  trigger:
    - platform: time
      at: '21:00:01'
    - platform: numeric_state
      entity_id: sensor.fan_temperature
      above: 29 # 升至高档
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.fan_temperature
      above: 25 # 升至中档
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: sensor.fan_temperature
      above: 24 # 升至低档
      for:
        minutes: 6
    - platform: numeric_state
      entity_id: sensor.fan_temperature
      below: 28 # 降至中档
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.fan_temperature
      below: 26 # 降至低档
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: sensor.fan_temperature
      below: 23 # 降至关机
      for:
        minutes: 6
  condition:
    - condition: time
      after: '20:30'
      before: '08:00'
  action:
    - service_template: '{% if (states("sensor.fan_temperature") | float > 23) %}fan.turn_on{% else %}fan.turn_off{% endif %}'
      entity_id: fan.fan
    - condition: numeric_state
      entity_id: sensor.fan_temperature
      above: 23
    - service: fan.set_speed
      data_template:
        entity_id: fan.fan
        speed: '{% if (states("sensor.fan_temperature") | float > 29) %}Level 3{% elif (states("sensor.fan_temperature") | float > 25) %}Level 2{% else %}Level 1{% endif %}'
    - delay: 1
    - service: logbook.log
      data_template:
        name: '{{ state_attr("sensor.fan_temperature", "friendly_name") }}={{ states("sensor.fan_temperature") }}'
        message: '{{ state_attr("fan.fan", "friendly_name") }}⇒{{ state_attr("fan.fan", "speed_level") }}'

# 书房风扇温度变化
- alias: Temperature Changed @Fan2
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: numeric_state
      entity_id: sensor.purifier6_temperature
      above: 30 # 升至高档
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.purifier6_temperature
      above: 26 # 升至中档
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: sensor.purifier6_temperature
      above: 24 # 升至低档
      for:
        minutes: 6
    - platform: numeric_state
      entity_id: sensor.purifier6_temperature
      below: 29 # 降至中档
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.purifier6_temperature
      below: 25 # 降至低档
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: sensor.purifier6_temperature
      below: 23 # 降至关机
      for:
        minutes: 6
  condition:
    - condition: time
      after: '20:00'
      before: '08:00'
  action:
    - service_template: '{% if (states("sensor.purifier6_temperature") | float > 23) %}fan.turn_on{% else %}fan.turn_off{% endif %}'
      entity_id: fan.fan2
    - condition: numeric_state
      entity_id: sensor.purifier6_temperature
      above: 23
    - service: fan.set_speed
      data_template:
        entity_id: fan.fan2
        speed: '{% if (states("sensor.purifier6_temperature") | float > 30) %}Level 3{% elif (states("sensor.purifier6_temperature") | float > 26) %}Level 2{% else %}Level 1{% endif %}'
    - delay: 1
    - service: logbook.log
      data_template:
        name: '{{ state_attr("sensor.purifier6_temperature", "friendly_name") }}={{ states("sensor.purifier6_temperature") }}'
        message: '{{ state_attr("fan.fan2", "friendly_name") }}⇒{{ state_attr("fan.fan2", "speed_level") }}'
