actuate:
  description: Tune entity based on sensor state
  fields:
    sensor_id:
      description: Sensor ID
      example: sensor.temperature
    sensor_attr:
      description: Sensor attribute key. Default means sensor state
      example: hcho
    sensor_values:
      description: Sensor value array
      example: '[23, 26, 30]'
    sensor_values_alt:
      description: Alternative sensor value array for deep night (2:00 am ~ 6:00 am)
      example: '[25, 28, 32]'
    entity_id:
      description: Entity ID to Tune
      example: fan.ceiling_fan
    entity_attr:
      description: Sensor attribute key. Default means entity state
      example: speed_level
    service:
      description: Service name to call. Default means set_{service_attr or entity_attr}
      example: fan.set_speed
    service_attr:
      description: Service attribute key. Deault means same as {entity_attr}
      example:
    entity_values:
      description: Entity value array for service call
      example: '[low, medium, high]'
